### PR TITLE
update to use 0.12 syntax

### PR DESCRIPTION
**Pull request by ryanking**

### CODE REVIEW

**Comment by justincc** [comment]
Hi @ryanking. Why do you want to make these changes? This repository is used only by HCA ingest and all code changes here (and in the DCP generally) are currently frozen.

**Comment by mweiden** [comment]
@justincc pardon the confusion here. @ryanking and I were talking about shaping up some of the other terraform we have and he proactively (and very helpfully) did it for all of the HCA org.

Up to you on whether you want to merge. It shouldn't have any affect on infra outcomes, just updating you so that you can use terraform 0.12.x (current release).

**Review by mweiden — APPROVED** [review]

**Comment by ryanking** [comment]
@mweiden do you want me to merge?

**Comment by justincc** [comment]
Thank you @mweiden. I think we will hold on merging until we know the roadmap for the DCP.

**Pull request closed without merging**
